<?php
namespace Webfactory\Dom;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-21 at 18:45:17.
 */
class XHTML10ParserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var XHTML10Parser
     */
    protected $parser;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->parser = new XHTML10Parser;
    }

    public function testParseDocument() {
        $data = '<root><bla>x</bla></root>';
        $expected = "<?xml version=\"1.0\"?>\n<root><bla>x</bla></root>\n";
        $document = $this->parser->parseDocument($data);

        $actual = $document->saveXML();
        $this->assertEquals($expected, $actual);
    }

    public function testParseFragment() {
        $data = '<root><bla>x</bla></root>';
        $expected = '<?xml version="1.0"?>' . "\n" . $this->wrapFragment($data) . "\n";
        $document = $this->parser->parseFragment($data);

        $actual = $document->saveXML();
        $this->assertEquals($expected, $actual);
    }

    protected function wrapFragment($fragment) {
        return '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">' . "\n"
            . '<html xmlns:esi="http://www.edge-delivery.org/esi/1.0" xmlns="'.XHTML10Parser::XHTMLNS.'">'
            . $fragment
            . '</html>';
    }

}
